

export default class Const {

    //平台
    static Platform = {
        normal: 0,
        android: 1,//安卓
        ios: 2,//ios
        browser:3,//浏览器
        wx: 4,
        qq:5,
    }
    //url 
    static Url = {
        HttpUrl: "http://www.kttread.com/api_v2/",
        HttpUrlTest: "http://120.55.42.179/api_v2/",
        HttpYHXY:"http://www.kttread.com/xieyi/xxds/use.html",//用户协议
        HttpYSZC:"http://www.kttread.com/xieyi/xxds/pri.html", //隐私政策
        HttpTestYHXY:"http://www.kttread.com/xieyi/xxds/use.html",//用户协议
        HttpTestYSZC:"http://www.kttread.com/xieyi/xxds/pri.html", //隐私政策
        QQConfigUrl:"https://h5game.99aly.com/5agamewx/alywx/htkj/wx/xiaoxiao/qq/config/qq_config.json",
        QQTaskUrl:"https://h5game.99aly.com/5agamewx/alywx/htkj/wx/xiaoxiao/qq/task/task.json"
    }
    static Adapter = {
        FightUIBottom:150,
        FightUITop:0,
    }
    static shareAdvShow = {
        share:0,
        adv : 1,
    }
    static Export = {
        isShow:true,
        iconUrl:"",
        exportUrl:"http://www.baidu.com"
    }  

    static AndroidEvent = {
        loginpageview:{
            eventID:"loginpageview",
            eventName:"登录按钮-界面"
        },
        login_guest:{
            eventID:"login-guest",
            eventName:"游客登录按钮"
        },
        login_weixin:{
            eventID:"login-weixin",
            eventName:"微信登录按钮"
        },
        gamemain:{
            eventID:"gamemain",
            eventName:"非第一次进入游戏界面"
        },
        new_gamemain:{
            eventID:"new-gamemain",
            eventName:"第一次进入游戏界面"
        },
        guide_1:{
            eventID:"guide-1",
            eventName:"新手引导—1"
        },
        guide_2:{
            eventID:"guide-2",
            eventName:"新手引导-2"
        },
        level_up:{
            eventID:"level-up",
            eventName:"过关成功"
        },
        wx_gamemain:{
            eventID:"wx-gamemain",
            eventName:"头像点击按钮"
        },
        shuaxin:{
            eventID:"shuaxin",
            eventName:"刷新按钮"
        },
        shipin_shuaxin:{
            eventID:"shipin-shuaxin",
            eventName:"获取刷新看视频"
        },
        chuizi:{
            eventID:"chuizi",
            eventName:"锤子按钮"
        },
        shipin_chuizi:{
            eventID:"shipin-chuizi",
            eventName:"获取锤子看视频"
        },
        huanse:{
            eventID:"huanse",
            eventName:"换色按钮"
        },
        shipin_huanse:{
            eventID:"shipin-huanse",
            eventName:"获取换色看道具"
        },
        xiaochu:{
            eventID:"xiaochu",
            eventName:"消除按钮"
        },
        zhadan:{
            eventID:"zhadan",
            eventName:"炸弹按钮"
        },
        shipin_xiaochu:{
            eventID:"shipin-xiaochu",
            eventName:"获取消除看视频"
        },
        qipao_exposure:{
            eventID:"qipao-exposure",
            eventName:"气泡显示"
        },
        qipao_click:{
            eventID:"qipao-click",
            eventName:"气泡点击"
        },
        shipin_shuangbei:{
            eventID:"shipin-shuangbei",
            eventName:"视频双倍"
        },
        qipao_close:{
            eventID:"qipao-close",
            eventName:"气泡弹出红包关闭"
        },
        guoguanshibai:{
            eventID:"guoguanshibai",
            eventName:"过关失败"
        },
        shipin_fuhuo:{
            eventID:"shipin-fuhuo",
            eventName:"失败看视频复活"
        },
        chongxinshiwan:{
            eventID:"chongxinshiwan",
            eventName:"失败重玩本关"
        },
        guoguanhongbao_exposure:{
            eventID:"guoguanhongbao-exposure",
            eventName:"过关红包弹框"
        },
        shipin_guoguanhongbao:{
            eventID:"shipin-guoguanhongbao",
            eventName:"看视频得到过关红包"
        },
        guanbihongbao:{
            eventID:"guanbihongbao",
            eventName:"关闭红包不弹视频"
        },
        guanbihongbao_quanping:{
            eventID:"guanbihongbao-quanping",
            eventName:"关闭红包弹视频"
        },
        yaoqinghongbao_exposure:{
            eventID:"yaoqinghongbao-exposure",
            eventName:"邀请红包弹框"
        },
        shipin_yaoqinghongbao:{
            eventID:"shipin-yaoqinghongbao",
            eventName:"看视频得到邀请红包"
        },
        fuzhi:{
            eventID:"fuzhi",
            eventName:"提现首页复制按钮"
        },
        shuruyaoqingma:{
            eventID:"shuruyaoqingma",
            eventName:"提现首页输入邀请码按钮"
        },
        tixianjine:{
            eventID:"tixianjine",
            eventName:"提现首页提现中间按钮"
        },
        tixian:{
            eventID:"tixian",
            eventName:"提现(微信头像)-游戏界面-点击"
        },
        wodeshuiguo:{
            eventID:"wodeshuiguo",
            eventName:"我的水果-游戏界面-点击"
        },
        shezhi:{
            eventID:"shezhi",
            eventName:"提现首页设置按钮"
        },
        meirifenhong:{
            eventID:"meirifenhong",
            eventName:"每日分红-点击-游戏界面"
        },
        choufenhong:{
            eventID:"choufenhong",
            eventName:"抽分红星-点击-游戏界面"
        },
        meirifuli:{
            eventID:"meirifuli",
            eventName:"每日福利-点击-游戏界面"
        },
        yingshouji:{
            eventID:"yingshouji",
            eventName:"赢手机-界面-点击"
        },
        dakatixian:{
            eventID:"dakatixian",
            eventName:"打卡提现-界面-点击"
        },
        tixianno_wbd:{
            eventID:"tixianno-wbd",
            eventName:"提现失败未绑定微信"
        },
        tixianno_tjbz:{
            eventID:"tixianno-tjbz",
            eventName:"提现失败条件不满足"
        },
        tixianno_wx:{
            eventID:"tixianno-wx",
            eventName:"提现失败微信未认证"
        },
        weixinfenxiang:{
            eventID:"weixinfenxiang",
            eventName:"邀请界面微信分享按钮"
        },
        fuzhiyaoqingma:{
            eventID:"fuzhiyaoqingma",
            eventName:"邀请界面邀请码按钮"
        },
        fuzhiyaoqinglianjie:{
            eventID:"fuzhiyaoqinglianjie",
            eventName:"邀请界面邀请链接按钮"
        },
        lmrwmktx:{
            eventID:"lwmktx",
            eventName:"领每日无门槛提现"
        },
        qutixian:{
            eventID:"qutixian",
            eventName:"去提现"
        },
        qiandaoshouji:{
            eventID:"qiandaoshouji",
            eventName:"签到赢手机-红包结果弹窗-点击"
        }
    }
    
}
